# Generated by Django 4.0.5 on 2022-09-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='staus',
            field=models.BooleanField(default=0, verbose_name='Модерированная'),
        ),
    ]
