# Generated by Django 4.0.5 on 2022-09-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_alter_quote_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='staus',
            new_name='status',
        ),
    ]
